# Generated by Django 3.2.5 on 2021-07-08 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadence', '0002_cadence_user'),
        ('accounts', '0002_account_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('cadence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadence.cadence')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
