# Generated by Django 3.2.5 on 2021-07-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_scripts', '0002_auto_20210708_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagescript',
            name='time_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
