# Generated by Django 3.2.5 on 2021-07-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_scripts', '0003_auto_20210708_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagescript',
            name='time_days',
            field=models.IntegerField(default=0),
        ),
    ]
