# Generated by Django 3.2.5 on 2021-07-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('acc_name', models.CharField(max_length=255)),
                ('acc_username', models.CharField(blank=True, max_length=255, null=True)),
                ('acc_id', models.IntegerField(unique=True)),
                ('sess_str', models.TextField()),
                ('phone', models.BigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
